version: '2'

services:
 v2ray:
    image: ephz3nt/v2ray_v3:go
    restart: always
    network_mode: "host"
    environment:
      sspanel_url: "https://v2vs.fun"
      key: "NimaQu"
      speedtest: 6
      node_id: 10
      api_port: 2333
      downWithPanel: 1
      TZ: "Asia/Shanghai"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"
